Issue 28
tl-its-umich-edu/runestone-scheduled-job pull request #29
Opened 2019-04-04 03:44 UTC by Adonais0

closes #28, closes #27 
- Removed `get_last_runtime`
- Update `cron_name` as a parameter
- Insert `success` or `failure` as cron_status depending on if `send_caliper_event` success

2019-04-08 14:49 UTC, jonespm commented on caliper_sender.py
> +        cron_status = "falure"
```suggestion
        cron_status = "failure"
```

2019-04-08 14:52 UTC, jonespm requested changes
Looks good, just one minor typo that I don't seem to be able to commit, then I'll commit this and send this to Michael this week. We'll want to test with the UDP too.

2019-04-09 18:21 UTC, jonespm approved these changes

2019-04-09 18:22 UTC, merged

2019-04-09 18:23 UTC, Adonais0 commented on caliper_sender.py
> +        cron_status = "falure"
Thanks, fixed!